from asset import Asset, TREE, STAR_TOPPER, RIBBONS, BAUBLES, GIFT_BOX1, GIFT_BOX2, GIFT_BOX3, GIFT_BOX4, WREATH, LOGO
from screener import Screener

tree = Asset(TREE)

star_topper = Asset(STAR_TOPPER,    blink_style = "permanent", color = [ "Yellow"])

ribbon5 = Asset(RIBBONS[1], blink_style = "random",color = [ "Red", "BrightMagenta"],  blink_rate = 4, blink_rate_init = 0)
ribbon1 = Asset(RIBBONS[0], blink_style = "random",color = [ "Red", "BrightMagenta"],  blink_rate = 4, blink_rate_init = 0)
ribbon2 = Asset(RIBBONS[1], blink_style = "random",color = [ "Red", "BrightMagenta"],  blink_rate = 4, blink_rate_init = 0,    reverse=True)
ribbon3 = Asset(RIBBONS[1], blink_style = "random",color = [ "Red", "BrightMagenta"],  blink_rate = 4, blink_rate_init = 0,    reverse=True).mirror_horizontal()
ribbon4 = Asset(RIBBONS[1], blink_style = "random",color = [ "Red", "BrightMagenta"],  blink_rate = 4, blink_rate_init = 0,    reverse=True)
ribbon5 = Asset(RIBBONS[1], blink_style = "random",color = [ "Red", "BrightMagenta"],  blink_rate = 4, blink_rate_init = 0)

BAUBLE_RAND_COLORS = [ "BrightRed", "BrightGreen", "BrightYellow", "BrightBlue", "BrightMagenta", "BrightCyan"]
bauble1 =   Asset(BAUBLES[0],    blink_style = "random",    color = BAUBLE_RAND_COLORS,    blink_rate = 2,    blink_rate_init = 0)
bauble2 =   Asset(BAUBLES[0],    blink_style = "random",    color = BAUBLE_RAND_COLORS,    blink_rate = 2,    blink_rate_init = 0)
bauble3 =   Asset(BAUBLES[0],    blink_style = "random",    color = BAUBLE_RAND_COLORS,    blink_rate = 2,    blink_rate_init = 0)
bauble4 =   Asset(BAUBLES[0],    blink_style = "random",    color = BAUBLE_RAND_COLORS,    blink_rate = 2,    blink_rate_init = 0)
bauble5 =   Asset(BAUBLES[0],    blink_style = "random",    color = BAUBLE_RAND_COLORS,    blink_rate = 2,    blink_rate_init = 0)
bauble6 =   Asset(BAUBLES[0],    blink_style = "random",    color = BAUBLE_RAND_COLORS,    blink_rate = 2,    blink_rate_init = 0)
bauble7 =   Asset(BAUBLES[0],    blink_style = "random",    color = BAUBLE_RAND_COLORS,    blink_rate = 2,    blink_rate_init = 0)
bauble8 =   Asset(BAUBLES[0],    blink_style = "random",    color = BAUBLE_RAND_COLORS,    blink_rate = 2,    blink_rate_init = 0)
bauble9 =   Asset(BAUBLES[0],    blink_style = "random",    color = BAUBLE_RAND_COLORS,    blink_rate = 2,    blink_rate_init = 0)
bauble10 =  Asset(BAUBLES[0],    blink_style = "random",    color = BAUBLE_RAND_COLORS,    blink_rate = 2,    blink_rate_init = 0)
bauble11 =  Asset(BAUBLES[0],    blink_style = "random",    color = BAUBLE_RAND_COLORS,    blink_rate = 2,    blink_rate_init = 0)
bauble12 =  Asset(BAUBLES[0],    blink_style = "random",    color = BAUBLE_RAND_COLORS,    blink_rate = 2,    blink_rate_init = 0)
bauble13 =  Asset(BAUBLES[0],    blink_style = "random",    color = BAUBLE_RAND_COLORS,    blink_rate = 2,    blink_rate_init = 0)
bauble14 =  Asset(BAUBLES[0],    blink_style = "random",    color = BAUBLE_RAND_COLORS,    blink_rate = 2,    blink_rate_init = 0)
bauble15 =  Asset(BAUBLES[0],    blink_style = "random",    color = BAUBLE_RAND_COLORS,    blink_rate = 2,    blink_rate_init = 0)

gift_box1           = Asset(GIFT_BOX1[0], blink_style = "permanent", color = [ "Blue"])
gift_box1_ribbon    = Asset(GIFT_BOX1[1], blink_style = "permanent", color = [ "Green"])
gift_box2           = Asset(GIFT_BOX2[0], blink_style = "permanent", color = [ "BrightRed"])
gift_box2_ribbon    = Asset(GIFT_BOX2[1], blink_style = "permanent", color = [ "Cyan"])
gift_box3           = Asset(GIFT_BOX3[0], blink_style = "permanent", color = [ "Green"])
gift_box3_ribbon    = Asset(GIFT_BOX3[1], blink_style = "permanent", color = [ "Red"])
gift_box4           = Asset(GIFT_BOX2[0], blink_style = "permanent", color = [ "White"])
gift_box4_ribbon    = Asset(GIFT_BOX2[1], blink_style = "permanent", color = [ "Red"])
gift_box5           = Asset(GIFT_BOX4[0], blink_style = "permanent", color = [ "BrightMagenta"])
gift_box5_ribbon    = Asset(GIFT_BOX4[1], blink_style = "permanent", color = [ "BrightYellow"])
gift_box6           = Asset(GIFT_BOX1[0], blink_style = "permanent", color = [ "BrightCyan"])
gift_box6_ribbon    = Asset(GIFT_BOX1[1], blink_style = "permanent", color = [ "BrightMagenta"])

wreath              = Asset(WREATH[0], blink_style = "permanent", color = [ "Green"])
wreath_ribbon       = Asset(WREATH[1], blink_style = "permanent", color = [ "Red"])
wreath_artifact     = Asset(WREATH[2], blink_style = "permanent", color = [ "Yellow"])
wreath_artifact2    = Asset(WREATH[3], blink_style = "permanent", color = [ "BrightYellow"])

logo = Asset(LOGO,    blink_style = "random", color = [ "BrightRed", "BrightGreen"], blink_rate=4)

screen = Screener(500, 200, fps=4)
offset_x = 50
offset_y = 10
screen.add_asset(tree, 10 + offset_x, 5 + offset_y)
screen.add_asset(logo, 240 + offset_x, 80 + offset_y)

screen.add_asset(star_topper, 135 + offset_x, 5 + offset_y)

screen.add_asset(ribbon1, 150 + offset_x, 50 + offset_y)
screen.add_asset(ribbon2, 80 + offset_x, 130 + offset_y)
screen.add_asset(ribbon3, 180 + offset_x, 110 + offset_y)
screen.add_asset(ribbon4, 120 + offset_x, 65 + offset_y)
screen.add_asset(ribbon5, 125 + offset_x, 90 + offset_y)

screen.add_asset(bauble1, 140 + offset_x, 25 + offset_y)
screen.add_asset(bauble2, 150 + offset_x, 30 + offset_y)
screen.add_asset(bauble3, 130 + offset_x, 37 + offset_y)
screen.add_asset(bauble4, 160 + offset_x, 40 + offset_y)
screen.add_asset(bauble5, 130 + offset_x, 50 + offset_y)
screen.add_asset(bauble6, 160 + offset_x, 60 + offset_y)
screen.add_asset(bauble7, 170 + offset_x, 70 + offset_y)
screen.add_asset(bauble8, 200 + offset_x, 72 + offset_y)
screen.add_asset(bauble9, 130 + offset_x, 78 + offset_y)
screen.add_asset(bauble10, 175 + offset_x, 84 + offset_y)
screen.add_asset(bauble11, 100 + offset_x, 90 + offset_y)
screen.add_asset(bauble12, 200 + offset_x, 93 + offset_y)
screen.add_asset(bauble13, 145 + offset_x, 100 + offset_y)
screen.add_asset(bauble14, 100 + offset_x, 115 + offset_y)
screen.add_asset(bauble15, 220 + offset_x, 132 + offset_y)

screen.add_asset(wreath, 117 + offset_x, 123 + offset_y)
screen.add_asset(wreath_ribbon, 117 + offset_x, 123 + offset_y)
screen.add_asset(wreath_artifact, 117 + offset_x, 123 + offset_y)
screen.add_asset(wreath_artifact2, 117 + offset_x, 123 + offset_y)

screen.add_asset(gift_box1, 60 + offset_x, 145 + offset_y)
screen.add_asset(gift_box1_ribbon, 60 + offset_x, 145 + offset_y)
screen.add_asset(gift_box2, 95 + offset_x, 137 + offset_y)
screen.add_asset(gift_box2_ribbon, 95 + offset_x, 137 + offset_y)
screen.add_asset(gift_box3, 120 + offset_x, 147 + offset_y)
screen.add_asset(gift_box3_ribbon, 120 + offset_x, 147 + offset_y)
screen.add_asset(gift_box6, 180 + offset_x, 142 + offset_y)
screen.add_asset(gift_box6_ribbon, 180 + offset_x, 142 + offset_y)
screen.add_asset(gift_box5, 190 + offset_x, 150 + offset_y)
screen.add_asset(gift_box5_ribbon, 190 + offset_x, 150 + offset_y)
screen.add_asset(gift_box4, 150 + offset_x, 142 + offset_y)
screen.add_asset(gift_box4_ribbon, 150 + offset_x, 142 + offset_y)

screen.start()